'leitprofil': |
  SELECT 
    LAND,
    SOEH_KRZ,
    SOEH_VAR,
    LAGENUM,
    HORIZONT,
    TIEFE_OG,
    TIEFE_UG
  FROM 
    03_LEITPROFIL;
      
'kartiereinheiten': |
  SELECT
    LAND, 
    TNR,
    ENR, 
    SOEH_NR,
    SOEH_KRZ, 
    SOEH_VAR,
    BODTYP, 
    NAEHR, 
    WASSER
  FROM 
    02_KARTIEREINHEITEN;

'feldkapazitaet': | 
  SELECT
    TNR,
    ENR,
    SOEH_NR,
    nfk_30, 
    nfk_60,
    nfk_80, 
    nfk_90, 
    nfk_100,
    nfk_160
  FROM 
    04_nFk_Dehner_et_al_2015_h0;